package com.xihua.easyctlserver.dao.model;

import java.util.Date;

public class Topic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topic
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    private String topic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.m_account
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    private String mAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.m_password
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    private String mPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.status
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.gmt_created
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.gmt_modified
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topic
     *
     * @return the value of topic.topic
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topic
     *
     * @param topic the value for topic.topic
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.m_account
     *
     * @return the value of topic.m_account
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    public String getmAccount() {
        return mAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.m_account
     *
     * @param mAccount the value for topic.m_account
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    public void setmAccount(String mAccount) {
        this.mAccount = mAccount == null ? null : mAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.m_password
     *
     * @return the value of topic.m_password
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    public String getmPassword() {
        return mPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.m_password
     *
     * @param mPassword the value for topic.m_password
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    public void setmPassword(String mPassword) {
        this.mPassword = mPassword == null ? null : mPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.status
     *
     * @return the value of topic.status
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.status
     *
     * @param status the value for topic.status
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.gmt_created
     *
     * @return the value of topic.gmt_created
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.gmt_created
     *
     * @param gmtCreated the value for topic.gmt_created
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.gmt_modified
     *
     * @return the value of topic.gmt_modified
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.gmt_modified
     *
     * @param gmtModified the value for topic.gmt_modified
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}