package com.xihua.easyctlserver.dao.model;

import java.util.Date;

public class TopicApi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_api.id
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_api.tid
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    private Long tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_api.api
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    private String api;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_api.params
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_api.action_name
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    private String actionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_api.gmt_created
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_api.gmt_modified
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_api.id
     *
     * @return the value of topic_api.id
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_api.id
     *
     * @param id the value for topic_api.id
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_api.tid
     *
     * @return the value of topic_api.tid
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_api.tid
     *
     * @param tid the value for topic_api.tid
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_api.api
     *
     * @return the value of topic_api.api
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    public String getApi() {
        return api;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_api.api
     *
     * @param api the value for topic_api.api
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    public void setApi(String api) {
        this.api = api == null ? null : api.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_api.params
     *
     * @return the value of topic_api.params
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_api.params
     *
     * @param params the value for topic_api.params
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_api.action_name
     *
     * @return the value of topic_api.action_name
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_api.action_name
     *
     * @param actionName the value for topic_api.action_name
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    public void setActionName(String actionName) {
        this.actionName = actionName == null ? null : actionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_api.gmt_created
     *
     * @return the value of topic_api.gmt_created
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_api.gmt_created
     *
     * @param gmtCreated the value for topic_api.gmt_created
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_api.gmt_modified
     *
     * @return the value of topic_api.gmt_modified
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_api.gmt_modified
     *
     * @param gmtModified the value for topic_api.gmt_modified
     *
     * @mbg.generated Sun Jan 14 00:24:49 CST 2024
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}