package com.xihua.easyctlserver.dao.model;

import java.util.Date;

public class UserAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.id
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.u_id
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.login_account
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    private String loginAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.login_password
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    private String loginPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.gmt_created
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.gmt_modified
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.id
     *
     * @return the value of user_auth.id
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.id
     *
     * @param id the value for user_auth.id
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.u_id
     *
     * @return the value of user_auth.u_id
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.u_id
     *
     * @param uId the value for user_auth.u_id
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.login_account
     *
     * @return the value of user_auth.login_account
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.login_account
     *
     * @param loginAccount the value for user_auth.login_account
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount == null ? null : loginAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.login_password
     *
     * @return the value of user_auth.login_password
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.login_password
     *
     * @param loginPassword the value for user_auth.login_password
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.gmt_created
     *
     * @return the value of user_auth.gmt_created
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.gmt_created
     *
     * @param gmtCreated the value for user_auth.gmt_created
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.gmt_modified
     *
     * @return the value of user_auth.gmt_modified
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.gmt_modified
     *
     * @param gmtModified the value for user_auth.gmt_modified
     *
     * @mbg.generated Sat Jan 13 00:56:41 CST 2024
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}