package com.xihua.easyctlserver.dao.model;

import java.util.Date;

public class UserTopicRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic_relation.id
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic_relation.u_id
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic_relation.u_tid
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    private Long uTid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic_relation.t_tid
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    private Long tTid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic_relation.gmt_created
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_topic_relation.gmt_modified
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic_relation.id
     *
     * @return the value of user_topic_relation.id
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic_relation.id
     *
     * @param id the value for user_topic_relation.id
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic_relation.u_id
     *
     * @return the value of user_topic_relation.u_id
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic_relation.u_id
     *
     * @param uId the value for user_topic_relation.u_id
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic_relation.u_tid
     *
     * @return the value of user_topic_relation.u_tid
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    public Long getuTid() {
        return uTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic_relation.u_tid
     *
     * @param uTid the value for user_topic_relation.u_tid
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    public void setuTid(Long uTid) {
        this.uTid = uTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic_relation.t_tid
     *
     * @return the value of user_topic_relation.t_tid
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    public Long gettTid() {
        return tTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic_relation.t_tid
     *
     * @param tTid the value for user_topic_relation.t_tid
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    public void settTid(Long tTid) {
        this.tTid = tTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic_relation.gmt_created
     *
     * @return the value of user_topic_relation.gmt_created
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic_relation.gmt_created
     *
     * @param gmtCreated the value for user_topic_relation.gmt_created
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_topic_relation.gmt_modified
     *
     * @return the value of user_topic_relation.gmt_modified
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_topic_relation.gmt_modified
     *
     * @param gmtModified the value for user_topic_relation.gmt_modified
     *
     * @mbg.generated Sun Jan 14 00:12:00 CST 2024
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}