package com.xihua.easyctlserver.dao.mapper;

import com.xihua.easyctlserver.dao.model.TopicApi;
import com.xihua.easyctlserver.dao.model.TopicApiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TopicApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_api
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    long countByExample(TopicApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_api
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    int deleteByExample(TopicApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_api
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_api
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    int insert(TopicApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_api
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    int insertSelective(TopicApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_api
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    List<TopicApi> selectByExample(TopicApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_api
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    TopicApi selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_api
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    int updateByExampleSelective(@Param("record") TopicApi record, @Param("example") TopicApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_api
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    int updateByExample(@Param("record") TopicApi record, @Param("example") TopicApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_api
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    int updateByPrimaryKeySelective(TopicApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_api
     *
     * @mbg.generated Sat Jan 06 22:48:59 CST 2024
     */
    int updateByPrimaryKey(TopicApi record);
}