package com.xihua.easyctlserver.dao.mapper;

import com.xihua.easyctlserver.dao.model.UserTopicRelation;
import com.xihua.easyctlserver.dao.model.UserTopicRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTopicRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_relation
     *
     * @mbg.generated Tue Jan 09 22:39:27 CST 2024
     */
    long countByExample(UserTopicRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_relation
     *
     * @mbg.generated Tue Jan 09 22:39:27 CST 2024
     */
    int deleteByExample(UserTopicRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_relation
     *
     * @mbg.generated Tue Jan 09 22:39:27 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_relation
     *
     * @mbg.generated Tue Jan 09 22:39:27 CST 2024
     */
    int insert(UserTopicRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_relation
     *
     * @mbg.generated Tue Jan 09 22:39:27 CST 2024
     */
    int insertSelective(UserTopicRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_relation
     *
     * @mbg.generated Tue Jan 09 22:39:27 CST 2024
     */
    List<UserTopicRelation> selectByExample(UserTopicRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_relation
     *
     * @mbg.generated Tue Jan 09 22:39:27 CST 2024
     */
    UserTopicRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_relation
     *
     * @mbg.generated Tue Jan 09 22:39:27 CST 2024
     */
    int updateByExampleSelective(@Param("record") UserTopicRelation record, @Param("example") UserTopicRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_relation
     *
     * @mbg.generated Tue Jan 09 22:39:27 CST 2024
     */
    int updateByExample(@Param("record") UserTopicRelation record, @Param("example") UserTopicRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_relation
     *
     * @mbg.generated Tue Jan 09 22:39:27 CST 2024
     */
    int updateByPrimaryKeySelective(UserTopicRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_topic_relation
     *
     * @mbg.generated Tue Jan 09 22:39:27 CST 2024
     */
    int updateByPrimaryKey(UserTopicRelation record);
}